### PR TITLE
Add OpenCV kernels proposal

### PR DESCRIPTION
**Pull request by jing-bao**
Hi, this a PR to add 3 opencv.js kernels as benchmark cases. The proposal is still in early stage, any comments are much appreciated!
cc @TianyouLi, cc the main contributor of this proposal @ZhiguoZh.

### CODE REVIEW

**Comment by wingo** [comment]
Neat!

Some thoughts from a random contributor:

1. Do you think it would make sense to check the benchmark into this proposal directly?  Obviously for benchmark users it would be nice to avoid requiring a build phase.  I think there's a stronger argument though, that the .wasm file may depend on the toolchain versions.

2. What do you think about #4 ?  Your thoughts are very welcome :)

**Comment by jing-bao** [comment]
> 1. Do you think it would make sense to check the benchmark into this proposal directly?  Obviously for benchmark users it would be nice to avoid requiring a build phase.  I think there's a stronger argument though, that the .wasm file may depend on the toolchain versions.

Actually the build phase is optional. The WASM code is embedded in opencv.js file. But the build phase is still valuable if we want to check the efficiency of different toolchains.

> 2. What do you think about #4 ?  Your thoughts are very welcome :)

To avoid too many details here, I commented on #4 directly :)

**Comment by titzer** [comment]
Ok, I had a look into this. I agree with Andy. Here we are using git submodules to pull in the opencv git repo, which has a build target for JS and wasm. What do you think of the following proposal:

1. We keep the openCV repo as the source of truth to track the evolution of OpenCV. I.e. we do not check in a full copy of that repo here.
2. We make a script in the openCV repo that can build wasm and package both the relevant source code and the relevant binaries into a structure suitable for this repo.

The above idea would be that this repo will always have a "pickled" copy of the OpenCV benchmark, including the source, build script, and wasm binaries.

3. We update this repo periodically (hopefully infrequently) with snapshots from the script from 2.)

What do you think?

**Comment by jing-bao** [comment]
Thanks for looking at this!

Maybe we can avoid using `git submodules` to pull the full OpenCV repo here. Instead, we use `build.sh` to pull a fixed tag/branch of OpenCV and run the build script inside OpenCV dir. The `build.sh` will have no effect on the benchmark repo if benchmark users don’t use it. And the benchmark repo always have wasm binaries, which we can update periodically (hopefully infrequently).

We try to avoid customizing a script in OpenCV to package partial source because the script may need to be updated with OpenCV updates. But of course, we are happy to do this if there’s specific reason. We can also make `build.sh` more general or integrate into the whole benchmark framework per requirements during benchmark usage.

What do you think of this?

**Comment by titzer** [comment]
Ok, what you propose above makes sense, as long as we believe the OpenCV repo won't go away entire :) Pinning to a specific branch or tag? I guess having a specific branch means that that branch could get up to date fixes, but the branch could also go away. I think a tag would be preferable, because that tag will never go away.

As part of the overall benchmarking strategy, maybe it makes sense for us to do a yearly, bi-yearly, or even longer time scale review of each specific item. E.g. the DaCapo benchmarks for Java undergone only 1 or 2 major revisions. Updating all the benchmark items pinned to specific commits might be part of that review process.

If you make the above changes then we can move forward.
Thanks!

**Comment by jing-bao** [comment]
Thanks for the comments! We will update the code to remove `git submodules` and update the WASM binaries.

**Comment by jing-bao** [comment]
Hi Ben, would you please take a look again? Thanks a lot!

**Comment by jing-bao** [comment]
Ping @titzer

**Review by titzer — APPROVED** [review]
lgtm, thanks!

**Pull request merged**
