### PR TITLE
Add Zen Garden load benchmark

### PR DESCRIPTION
**Pull request by wingo**
Builds on #3.  A little gnarly because I don't know the copyright for the zen garden demo, and I don't know how to rebuild it.  Can take down this PR if it turns out that the rights aren't there.

### CODE REVIEW

**Review by titzer — COMMENTED** [review]
Generally approve of this direction. I think it totally makes sense to have load time benchmarks. I am not sure how to force all engines to do compilation. JSC, up until about 6 months ago, was compiling at instantiation time, but now they have added an interpreter tier. Nevertheless that interpreter tier does require some translation, so it is on the critical path.

I guess instantiation time is a good-enough standin for startup latency/compile time now.

If we can get more clarity on the license, then I'll take a closer look here and hopefully we can merge it in.

**Comment by wingo** [comment]
Heya :)  I think forcing compilation isn't necessarily the goal, fwiw -- the metric is really time-to-interactivity; other aspects of interactivity (throughput, jankiness, etc) aren't measured here.

FWIW I looked into this issue and fwiw JSC's bytecode emitter for their interpreter tier has similar overhead to V8's liftoff or spidermonkey's baseline compiler: https://wingolog.org/archives/2020/04/14/understanding-webassembly-code-generation-throughput

**Comment by titzer** [comment]
This demo is from Epic, correct? Are you able to contact someone there to find out about the license?

**Comment by wingo** [comment]
I reached out through Mozilla contacts and got confirmation from Tim Sweeney at Epic that it is free to use in this context.  Specifically that the zen garden demo is "licensed for any use with UE4", as noted here:

  https://www.unrealengine.com/marketplace/en-US/product/epic-zen-garden

That web page currently says "Licensed For Use Only with Unreal Engine-based Products", which evidently this is such a use.

This is less specific than I would like and is not an open source license, but it may be sufficient just for the purposes of having a pile of WebAssembly to throw at a compiler for testing throughput.

**Review by titzer — APPROVED** [review]

**Pull request merged**
